docs/termos/copiatermos
copiando termos de uso e politica de privacidade atualizados
=> Copia termos de uso

esqueletoArtefatos, metodologia.md
Foi criado o artefato metodologia, que define como o projeto vai ser desenvolvido.
Issue #3
=> Metodologia

docs/atas/ata_reuniao_03.md
Pull request da ata da reunião 03 que ocorreu dia 19/09/2023
Nenhuma issue foi aberta para esse pull request.
=> Ata reuniao 03

docs/atas/ata_reuniao_03.md, docs/atas/ata_reuniao_04.md
Criação da ata da reunião 4 que ocorreu dia 20/09/2023 às 20:00
=> Ata reuniao 04

docs/atas/ata_reuniao_01.md, docs/atas/ata_reuniao_02.md, docs/atas/ata_reuniao_03.md, docs/atas/ata_reuniao_04.md, docs/atas/esqueleto_de_ata.md
Adição do horário de fim das atas no esqueleto da ata e nas atas 01, 02, 03 e 04.
=> Feature update atas

docs/lexico.md, docs/planejamento/aplicativoEscolhido.md, docs/planejamento/aplicativoescolhido.md, docs/planejamento/metodologia.md
Descrever de forma objetiva e coerente o que foi feito
Issue #44
=> Feature lexico

docs/atas/ata_reuniao_09.md
Foi feita a documentação da Ata 09 da reunião do dia 25/10/2023
Nenhuma issue foi atribuída ao pull request
=> Ata da reunião 09

docs/historiasdeusuario.md
Artefato Histórias de Usuário para a entrega 4.
=> Feature historias de usuario

docs/modelagem/agil/backlog.md, docs/modelagem/backlogs.md, docs/modelagem/product-backlog.md, docs/planejamento/CronogramaExecutado.md
Atualização do documento de cronograma executado de acordo com a entrega 3 e a entrega 4.
Issue #56 : Atualizar Cronograma Executado.
=> Feature cronograma executado etapa 3 e etapa 4

docs/atas/ata_reuniao_10.md
Criação da ata da reunião 10 que ocorreu dia 30/10/2023 às 20:57.
=> Feature ata reuniao 10

docs/apresentacoes/apresentacao04.md
Atualização do documento de apresentações, para a apresentação 04 do dia 07/11/2023.
=> Feature apresentacao04

docs/atas/ata_reuniao_01.md, docs/atas/ata_reuniao_02.md, docs/atas/ata_reuniao_10.md, docs/atas/ata_reuniao_11.md
Criação da ata da reunião 11 que ocorreu dia 08/11/2023 às 21:04
=> Feature ata reuniao 11

docs/verificacao/verificacaoGrupo+1/etapa1/metodologia.md, docs/verificacao/verificacaoGrupo+1/etapa2/observacao.md, docs/verificacao/verificacaoGrupo+1/etapa2/personas.md, docs/verificacao/verificacaoGrupo+1/etapa3/lexicos.md
Foi criado os artefatos das tarefas.
Issues #70
=> Feature verificacao mo

docs/verificacao/verificacaoGrupo+1/etapa1/PlanejamentoVerificacaoEtapa1.md, docs/verificacao/verificacaoGrupo+1/etapa2/PlanejamentoVerificacaoEtapa2.md, docs/verificacao/verificacaoGrupo+1/etapa2/observacao.md, docs/verificacao/verificacaoGrupo+1/etapa3/PlanejamentoVerificacaoEtapa3.md
Será criado os artefatos das verificações de Metodologia, Personas, Léxicos e Observação.
=> [Verificação] Adicionando tabelas específicas nos documentos de planejamento

docs/planejamento/aplicativoescolhido.md, docs/verificacao/verificacaoGrupo+1/etapa1/PlanejamentoVerificacaoEtapa1.md, docs/verificacao/verificacaoGrupo+1/etapa1/richPicture.md, docs/verificacao/verificacaoGrupo+1/etapa2/MoSCoW.md, docs/verificacao/verificacaoGrupo+1/etapa2/PlanejamentoVerificacaoEtapa2.md, docs/verificacao/verificacaoGrupo+1/etapa2/TLS.md, docs/verificacao/verificacaoGrupo+1/etapa4/PlanejamentoVerificacaoEtapa4.md, docs/verificacao/verificacaoGrupo+1/etapa4/backlog.md
Criação da branch contendo a verificação de 4 artefatos do grupo 5- Jitsi.
Issue #72
=> Feature verificacao mariiana

docs/planejamento/CronogramaExecutado.md
Alteração no cronograma executado para incluir a entrega 5.1 e entrega 6.
Resolve a issue #79 de cronograma executado
=> [UPDATE] cronograma executado entrega 5.1 e entrega 6

docs/elicitacao/tecnicas/entrevista.md, docs/elicitacao/tecnicas/introspeccao.md, docs/elicitacao/tecnicas/storytelling.md, docs/planejamento/aplicativoEscolhido.md, docs/planejamento/metodologia.md, docs/verificacao/verificacaoGrupo4/etapa2/entrevista.md
Foi  realizado as correções nos artefatos que a maria Barbosa criou na parte de planejamento e de elicitação.
resolve parcialmente a Issue #99
=> Feature correcao madu barbosa

docs/elicitacao/tecnicas/questionario.md, docs/modelagem/agil/backlog.md, docs/modelagem/especificacao-suplementar.md, docs/pos-rastreabilidade/backwardFrom.md
foi feito nessa branch a correção dos artefatos, brainstorming, questionario, backlog, especificação suplementar e backWard-From.
Issue ##105 e #106  foi resolvida com o pull request
=> Feature fix esther

docs/validacao/consolidacoes.md
Adição do vídeo de consolidação de histórias de usuário com Mateus e João
Issues  #127
=> Feature consolidação Mariiana Siqueira

docs/entrega-final/artefatos_criados_e_execucao_do_projeto.md
Foi realizado  o artefato de artefatos criados e execucao do projeto da parte da maria Barbosa!
Issue #139
=> Entrega final por maduB

docs/entrega-final/app_selecionado_e_ferramentas_utilizadas.md, docs/verificacao/verificacaoGrupo4/etapa2/$100.md, docs/verificacao/verificacaoGrupo4/etapa2/firstThingsFirst.md, docs/verificacao/verificacaoGrupo4/etapa3/lexicos.md, docs/verificacao/verificacaoGrupo4/etapa6/matriz.md
Foi realizado  o artefato de app selecionado e ferramentas usadas e também resultados final.
Issue #141
=> Feature entrega final esther
